// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contoso_receipt_backend.Classes;

#nullable disable

namespace contoso_receipt_backend.Migrations
{
    [DbContext(typeof(ContosoDbContext))]
    [Migration("20260116221201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("contoso_receipt_backend.Classes.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Merchant", b =>
                {
                    b.Property<string>("Proper_name")
                        .HasColumnType("TEXT");

                    b.HasKey("Proper_name");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Receipts.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Proper_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Receipt_date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total_amount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Name");

                    b.HasIndex("Proper_name");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Statuses.Status", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Statuses.StatusChange", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("Old_status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("New_status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.HasKey("Email", "Old_status", "New_status");

                    b.ToTable("StatusChanges");
                });

            modelBuilder.Entity("contoso_receipt_backend.User", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Administrators.Administrator", b =>
                {
                    b.HasBaseType("contoso_receipt_backend.User");

                    b.ToTable("Administrators", (string)null);
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Employees.Employee", b =>
                {
                    b.HasBaseType("contoso_receipt_backend.User");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Reviewers.Reviewer", b =>
                {
                    b.HasBaseType("contoso_receipt_backend.User");

                    b.ToTable("Reviewers", (string)null);
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Receipts.Receipt", b =>
                {
                    b.HasOne("contoso_receipt_backend.Classes.Users.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("Email")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("contoso_receipt_backend.Classes.Category", null)
                        .WithMany()
                        .HasForeignKey("Name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("contoso_receipt_backend.Classes.Merchant", null)
                        .WithMany()
                        .HasForeignKey("Proper_name")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Statuses.StatusChange", b =>
                {
                    b.HasOne("contoso_receipt_backend.User", null)
                        .WithMany()
                        .HasForeignKey("Email")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Administrators.Administrator", b =>
                {
                    b.HasOne("contoso_receipt_backend.User", null)
                        .WithOne()
                        .HasForeignKey("contoso_receipt_backend.Classes.Users.Administrators.Administrator", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Employees.Employee", b =>
                {
                    b.HasOne("contoso_receipt_backend.User", null)
                        .WithOne()
                        .HasForeignKey("contoso_receipt_backend.Classes.Users.Employees.Employee", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("contoso_receipt_backend.Classes.Users.Reviewers.Reviewer", b =>
                {
                    b.HasOne("contoso_receipt_backend.User", null)
                        .WithOne()
                        .HasForeignKey("contoso_receipt_backend.Classes.Users.Reviewers.Reviewer", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
